### ISSUE TITLE
Unnecessary dependency on islandora_defaults

### ISSUE THREAD

**Issue by ajstanley** [Islandora/islandora_mirador#10]
**What steps does it take to reproduce the issue?**

* Run `drush en islandora_mirador after `running `composer require islandora/islandora_mirador` on a fresh build (Playbook, in my case)

* What happens?
```
In UnmetDependenciesException.php line 100:
                                                                                                                                                                                     
  Configuration objects provided by <em class="placeholder">islandora_mirador</em> have unmet dependencies: <em class="placeholder">core.entity_view_display.node.islandora_object.  
  mirador (islandora_defaults)</em>     
```                                                                                                                                             
                                
Deleting the offending lines allows the module to install, and it all seems to work as it's meant to.

**Which version of Islandora are you using?**

Islandora 2.4.5

**Any related open or closed issues to this bug report?**

**Screenshots:**

**Comment by alxp** [comment]
There's an open PR for this, just moving the configs to optional: https://github.com/Islandora/islandora_mirador/pull/9

**Comment by alxp** [comment]
Resolved with PR
