### ISSUE TITLE
[BUG] `hook_install()` term creation failures during site installation from `--existing-config`

### ISSUE THREAD

**Issue by adam-vessey** [Islandora/islandora_mirador#13]
**What steps does it take to reproduce the issue?**

* When does this issue occur?

Site installation using an `--existing-config`, with this module enabled.

* Which page does it occur on?

N/A

* What happens?

Don't recall the exact error, but it will attempt to create the term before the `islandora_display` taxonomy itself is configured, due to the site installation flow ([was encountered previously with `islandora_fits` when dealing with the `islandora-starter-site`](https://github.com/roblib/islandora_fits/pull/14)):
* enabling the module and running install hooks; before
* importing the existing configuration (which defines the taxonomy)

... looking back at https://github.com/roblib/islandora_fits/issues/12 , I'm not sure there's an explicit error, but just that the term will probably not carry [the intended value for `field_external_uri`](https://github.com/Islandora/islandora_mirador/blob/b9d0939f153e4ffdea77592085132b67ebb40fa0/islandora_mirador.install#L36), but will instead be left blank.

* To whom does it occur (anonymous visitor, editor, administrator)?

Sys admin.

* What did you expect to happen?

The term to be able to be created without error.

**Which version of Islandora are you using?**

N/A

**Any related open or closed issues to this bug report?**

Same class of issue as https://github.com/roblib/islandora_fits/pull/14

**Screenshots:**

**Comment by rosiel** [comment]
I prefer (and seemed to have convinced others?) that we should take all the default config stuff including this term out, and put it in the Starter Site.
