### ISSUE TITLE
[FEATURE] Hide Mirador when the manifest is empty.

### ISSUE THREAD

**Issue by rosiel** [Islandora/islandora_mirador#33]
**Overview of feature request**
 
Hide the viewer when empty.
 
**What kind of user is the feature intended for?**
User, Site Designer
 
**What inspired the request?**
 The Mirador viewer still shows up - showing 1 of 0 - when the manifest is empty.
 
**What existing behavior do you want changed?**
 That the viewer shows up when empty.
 
**Any brand new behavior do you want to add to Islandora?**
 I want it to be hide-able when empty.
 
**Any related open or closed issues to this feature request?**
No

<img width="843" alt="Screenshot 2023-09-25 at 10 12 59 AM" src="https://github.com/Islandora/islandora_mirador/assets/1943338/5a246dec-a7a8-4ffd-ad7b-3e12002ffd15">

**Comment by alxp** [comment]
I wonder if we could make this a feature request to Mirador itself, perhaps that it fold itself into a compact view when there's no content.

This is useful either way though so I support this feature and might be able to get time to work on it.

**Comment by rosiel** [comment]
For the moment we can use Contexts to hide the viewer, for example, require the condition "Node is referenced by other nodes" and use field_member_of, which will activate the context only for nodes with members.
