### ISSUE TITLE
[FEATURE] Support Mirador plugins

### ISSUE THREAD

**Issue by alxp** [Islandora/islandora_mirador#4]
**Overview of feature request**

Allow Mirador plugins to be enabled and configured inside the Drupal admin interface. 
 
**What kind of user is the feature intended for?**
Site builder, Developer
 
 
**What inspired the request?**
 
Mirador has a plugin architecture where the plugins are configured via a config array when instantiated in Javascript and IIIF contents. Islandora should support the ability to use these plugins without hardcoding it.
 
**What existing behavior do you want changed?**
 
All Mirador configuration is currently hard-coded in the module.
 
**Any brand new behavior do you want to add to Islandora?**
 
On the Admin settings page :

- Show a list of plugins that are available. Auto-detection may be difficult but could be done.
- Include a hook to alter the configuration form so custom per-plugin settings can be declared by a submodule or third-party module.
- Hooks to alter the instantiation of the Mirador Viewer app based on these settings.
- Hooks to alter the IIIF Manifest generation process based on these settings.

 
**Any related open or closed issues to this feature request?**
Use Case https://github.com/Islandora/islandora_mirador/issues/2

**Comment by noahwsmith** [comment]
@alxp I'd like to test HOCR in the Mirador viewer - it sounds like you're working towards this from what I can read in https://github.com/Islandora/islandora_mirador/wiki/Notes-on-developing-more-robust-Mirador-support-in-Drupal-and-Islandora

How could we best collaborate with you on this?

**Comment by alxp** [comment]
Hi @noahwsmith , I've been doing some yak shaving due to moving computers and trying to make ISLE-DC my daily driver but I've got a mirador build with plugins and a islandora_mirador PR ready to go so I'll try and open those up in the next day or so.

Best,

 - Alexander

**Comment by noahwsmith** [comment]
Fabulous! We'll look forward to it, and will dive right in to help test when it's ready! cc @wgilling @dannylamb @patdunlavey @dmer

**Comment by alxp** [comment]
Hi Noah, I’ve just created a pull request with a updated Mirador module that supports plug-ins. https://github.com/Islandora/islandora_mirador/pull/14

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
